In [20]:
import pandas as pd

df = pd.read_csv('prepped_diabetes_data.csv', index_col='Patient number')
df

,Cholesterol,Glucose,HDL Chol,Age,Gender,Height,Weight,BMI,Systolic BP,Diastolic BP,waist,hip,Diabetes,waist_hip_ratio,hdl_chol_ratio
Patient number,,,,,,,,,,,,,,,
1,193,77,49,19,1,61,119,22.5,118,70,32,38,0,0.842105,0.253886
2,146,79,41,19,1,60,135,26.4,108,58,33,40,0,0.825000,0.280822
3,217,75,54,20,1,67,187,29.3,110,72,40,45,0,0.888889,0.248848
4,226,97,70,20,1,64,114,19.6,122,64,31,39,0,0.794872,0.309735
5,164,91,67,20,1,70,141,20.2,122,86,32,39,0,0.820513,0.408537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,227,105,44,83,1,59,125,25.2,150,90,35,40,0,0.875000,0.193833
387,226,279,52,84,1,60,192,37.5,144,88,41,48,1,0.854167,0.230088
388,301,90,118,89,1,61,115,21.7,218,90,31,41,0,0.756098,0.392027
389,232,184,114,91,1,61,127,24.0,170,82,35,38,1,0.921053,0.491379
390,165,94,69,92,1,62,217,39.7,160,82,51,51,0,1.000000,0.418182

In [21]:
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

In [24]:
automl = setup(df, target='Diabetes')

In [30]:
automl[6]

,Cholesterol,Glucose,HDL Chol,Age,Height,Weight,BMI,Systolic BP,Diastolic BP,waist,hip,waist_hip_ratio,hdl_chol_ratio,Gender_0
Patient number,,,,,,,,,,,,,,
8,164.0,71.0,63.0,20.0,72.0,145.0,19.700001,108.0,78.0,29.0,36.0,0.805556,0.384146,1.0
169,269.0,59.0,66.0,41.0,67.0,191.0,29.900000,130.0,73.0,38.0,41.0,0.926829,0.245353,1.0
51,164.0,94.0,58.0,28.0,67.0,180.0,28.200001,128.0,94.0,39.0,43.0,0.906977,0.353659,0.0
242,218.0,182.0,54.0,51.0,66.0,215.0,34.700001,139.0,69.0,42.0,53.0,0.792453,0.247706,0.0
260,216.0,79.0,46.0,54.0,65.0,138.0,23.000000,132.0,80.0,33.0,39.0,0.846154,0.212963,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,300.0,65.0,59.0,34.0,65.0,160.0,26.600000,120.0,60.0,40.0,47.0,0.851064,0.196667,0.0
137,268.0,90.0,48.0,38.0,63.0,181.0,32.099998,142.0,100.0,38.0,46.0,0.826087,0.179104,0.0
112,179.0,81.0,35.0,36.0,63.0,125.0,22.100000,110.0,76.0,33.0,36.0,0.916667,0.195531,0.0
191,244.0,101.0,39.0,44.0,71.0,168.0,23.400000,140.0,89.0,36.0,39.0,0.923077,0.159836,1.0
30,164.0,86.0,40.0,23.0,69.0,245.0,36.200001,126.0,75.0,44.0,47.0,0.936170,0.243902,0.0

In [31]:
best_model = compare_models()

In [38]:
best_model

sklearn.discriminant_analysis.LinearDiscriminantAnalysis

In [36]:
df.iloc[-2:-1].shape

(1, 15)

In [37]:
predict_model(best_model, df.iloc[-2:-1])

,Cholesterol,Glucose,HDL Chol,Age,Gender,Height,Weight,BMI,Systolic BP,Diastolic BP,waist,hip,Diabetes,waist_hip_ratio,hdl_chol_ratio,Label,Score
Patient number,,,,,,,,,,,,,,,,,
389,232,184,114,91,1,61,127,24.0,170,82,35,38,1,0.921053,0.491379,0,0.5096

In [39]:
save_model(best_model, 'LDA')

Transformation Pipeline and Model Succesfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='Diabetes',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_str...
                 ('dummy', Dummify(target='Diabetes')),
                 ('fix_perfect', Remove_100(target='Diabetes')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  LinearDiscriminantAnalysis(n_components=None, priors=None,
                                             shrinkage=None, solver='svd',
                                             store_covariance=False,
                                             tol=0.0001)]],
          verbose=False),
 'LDA.pkl')

In [11]:
import pickle

with open('LDA_model.pk', 'wb') as f:
    pickle.dump(best_model, f)

In [12]:
with open('LDA_model.pk', 'rb') as f:
    loaded_model = pickle.load(f)

In [13]:
new_data = df.iloc[-2:-1].copy()
new_data.drop('Diabetes', axis=1, inplace=True)
loaded_model.predict(new_data)

array([1])

In [41]:
loaded_lda = load_model('LDA')

Transformation Pipeline and Model Successfully Loaded

In [42]:
predict_model(loaded_lda, new_data)

,Cholesterol,Glucose,HDL Chol,Age,Gender,Height,Weight,BMI,Systolic BP,Diastolic BP,waist,hip,waist_hip_ratio,hdl_chol_ratio,Label,Score
Patient number,,,,,,,,,,,,,,,,
389,232,184,114,91,1,61,127,24.0,170,82,35,38,0.921053,0.491379,0,0.5096

In [48]:
from IPython.display import Code

Code('predict_diabetes.py')

import pandas as pd
from pycaret.classification import predict_model, load_model

def load_data(filepath):
    """
    Loads diabetes data into a DataFrame from a string filepath.
    """
    df = pd.read_csv(filepath, index_col='Patient number')
    return df


def make_predictions(df):
    """
    Uses the pycaret best model to make predictions on data in the df dataframe.
    """
    model = load_model('LDA')
    predictions = predict_model(model, data=df)
    predictions.rename({'Label': 'Diabetes_prediction'}, axis=1, inplace=True)
    predictions['Diabetes_prediction'].replace({1: 'Diabetes', 0: 'No diabetes'},
                                            inplace=True)
    return predictions['Diabetes_prediction']


if __name__ == "__main__":
    df = load_data('data/new_diabetes_data.csv')
    predictions = make_predictions(df)
    print('predictions:')
    print(predictions)

In [49]:
%run predict_diabetes.py

Transformation Pipeline and Model Successfully Loaded
predictions:
Patient number
391       Diabetes
392    No diabetes
393    No diabetes
394    No diabetes
Name: Diabetes_prediction, dtype: object

Summary and Short Analysis

This week assignment is about automation techniques for data science with Python. First we loaded the same prepared data from week 2 where everything has been converted to numbers. Second, we used pycart for autoML but before doing that we installed Python package with condo. Then we import the function we need. After that, we satup our autoML and we basically run the autoML to find the best model.But before we run our autoML to find the best model, we have if our datatypes of the input are correct and in our case, they were fine. This is updated in real time within the notebook as needed.
Boosting algorithms such as xgboost and catboost take the longest to run.
xgboost is frequently towards the top. To use xgboost and lightgbm, we must either enable preprocessing (which transforms categorical columns to numeric columns) or set our categorical columns to numeric using 'automl = setup(df, target='Diabetes', preprocess=False, numeric features= Gender). Our best model object now contains the highest-scoring model.We can also use the 'compare models' argument'sort' to select another metric as our scoring metric.
It employs precision by default (and we can see the table above is sorted by accuracy). We may set this to'sort='Precision" to utilize precision (TP / (TP + FN)), for example. we found out that our best mpdel is LDA. Third, we used our best_model to make predictions. We selected the last row, but using the indexing [-2:-1] to make it 2D array instead of 1D. From there, we can see this creates a new column, 'Score' with the propability of class1. It also creates a 'Label' column with the predicted label, where it rounds up if score is >=0.5 (greater than or equal to 0.5). Finally,we stored our trained model so we can utilize it later in a Python file.For instance, pycaret includes a convenient method that saves the model as a pickle file. In this case, we utilize the built-in 'open' function to open a file called 'LDA model.pk,' then open it for writing with "w" and in binary format with "b."That file object is saved in the variable 'f.'After we exit the with statement, the file is automatically closed; otherwise, we must use the method 'close' from the file object 'f'. Pickle is then used to store our data to a file. After that, we saved our code to GitHub.